"use strict";
import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';

import NavButton from './nav-button.jsx';

const NavBar = () => {
    return (
        // navigation bar-- to be put into each page
        <nav className = "poem-nav">
            <BrowserRouter>
                <section className = "nav-header">
                    <strong>Navigation</strong>
                </section>
                <section className = "poem-search">
                    <input type = "search" className = "search-bar"></input> <button className = "poem-search-button">🔍</button>
                </section>
                <section className = "featured">
                    <Link to = "./display.html">display page access for now</Link>
                </section>
                <section className = "submission">
                    <Link to = "./submit.html">submit a poem</Link>
                </section>
                {/* this'll be a list of poems pulled from storage, will be generated by views or by random */}
                <section className = "poem-list">
                    <button className = "poem-entry">example 1</button>
                    <button className = "poem-entry">example 2</button>
                    <button className = "poem-entry">example 3</button>
                    <button className = "poem-entry">example 4</button>
                    <button className = "poem-entry">example 5</button>
                </section>
            </BrowserRouter>
        </nav>
    );
};

export default NavBar;
