"use strict";
import { useState } from 'react';
import { createRoot } from 'react-dom/client';

const NavBar = () => {
    return (
        // navigation bar-- to be put into each page
        <nav className = "poem-nav">
                <section className = "nav-header">
                    <strong>Navigation</strong>
                </section>
                <section className = "poem-search">
                    <input type = "search" className = "search-bar"></input> <button className = "poem-search-button">🔍</button>
                </section>
                <section className = "featured">
                    <a href = "./display.html">display page access for now</a>
                </section>
                <section className = "submission">
                    <a href = "./submit.html">submit a poem</a>
                </section>
                {/* this'll be a list of poems pulled from storage, will be generated by views or by random */}
                <section className = "poem-list">
                    <button className = "poem-entry">example 1</button>
                    <button className = "poem-entry">example 2</button>
                    <button className = "poem-entry">example 3</button>
                    <button className = "poem-entry">example 4</button>
                    <button className = "poem-entry">example 5</button>
                </section>
        </nav>
    );
};

export default NavBar;
