"use strict";
import { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';

const NavBar = () => {
    // #region inserting the repoemAPI fetch here too-- will be used for navigating and calling pages
        const [poemsData, setPoemsData] = useState([]);
        const [dataIsLoaded, setDataIsLoaded] = useState(false);
    
        useEffect(() => {
                fetch('http://localhost:8080/data/poems')
                .then((res) => res.json())
                .then((json) => {
                    setPoemsData(json);
                    setDataIsLoaded(true);
                });
        }, []);
    
        if (!dataIsLoaded) {
            return (
                <div>
                    <h1>Please wait...</h1>
                </div>
            );
        }
    // #endregion

    // #region creating button entries for nav bar-- randomized entries
    // #endregion
    
    return (
        // navigation bar-- to be put into each page
        <nav className = "poem-nav">
                <section className = "nav-header">
                    <strong>Navigation</strong>
                </section>
                <section className = "featured">
                    <a href = "./display.html">poem collection</a>
                </section>
                <section className = "submission">
                    <a href = "./submit.html">submit a poem</a>
                </section>
                {/* this'll be a list of poems pulled from storage, will be generated by views or by random */}
                <section className = "poem-list">
                    <button className = "poem-entry">example 1</button>
                    <button className = "poem-entry">example 2</button>
                    <button className = "poem-entry">example 3</button>
                    <button className = "poem-entry">example 4</button>
                    <button className = "poem-entry">example 5</button>
                </section>
        </nav>
    );
};

export default NavBar;
